switch-arch: make the fcode-utils tokeniser "toke" mandatory for the build
Signed-off-by: Mark Cave-Ayland <mark.cave-ayland@ilande.co.uk>

git-svn-id: svn://coreboot.org/openbios/trunk/openbios-devel@1191 f158a5a8-5612-0410-a976-696ce0be7e32

diff --git a/config/scripts/switch-arch b/config/scripts/switch-arch
--- a/config/scripts/switch-arch
+++ b/config/scripts/switch-arch
@@ -117,6 +117,11 @@ config_set_boolean()
     echo "<option name=\"$option\" type=\"boolean\" value=\"true\" />"
 }
 
+exists()
+{
+    type "$1" >/dev/null 2>&1
+}
+
 
 SRCDIR=`dirname "$0"`/../..
 BUILDDIR=`pwd`
@@ -131,6 +136,13 @@ fi
 VERSION=`head $SRCDIR/VERSION`
 
 echo "Configuring OpenBIOS on $HOSTARCH for $*"
+
+if exists toke; then
+    :
+else
+    echo "Unable to locate toke executable from the fcode-utils package - aborting"
+    exit 1
+fi
 
 target_list=""
 for target in $*; do
