Fix a typo
Signed-off-by: Blue Swirl <blauwirbel@gmail.com>

git-svn-id: svn://coreboot.org/openbios/trunk/openbios-devel@649 f158a5a8-5612-0410-a976-696ce0be7e32

diff --git a/config/scripts/switch-arch b/config/scripts/switch-arch
--- a/config/scripts/switch-arch
+++ b/config/scripts/switch-arch
@@ -96,7 +96,7 @@ select_prefix()
     if [ "$ARCH" = "$HOSTARCH" ]; then
         return
     fi
-    echo "ERROR: no ${1} cross-compiler found !" 1>&2
+    echo "ERROR: no ${1} cross-compiler found !" 1>&2
     exit 1
 }
 
